kind: Service
apiVersion: v1
metadata:
  name: probation-court-prototype
spec:
  selector:
    app: probation-court-prototype
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
  type: NodePort
